name: Build and Deploy TerriaJS Viewer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./  # root folder of your repo; adjust if needed

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --legacy-peer-deps

      - name: Run lint
        run: yarn gulp lint

      - name: Build project
        run: yarn gulp build

      - name: Release
        run: yarn gulp release

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: wwwroot

      # Uncomment to add Docker build and push steps later
      # - name: Docker Build + Push
      #   run: yarn docker-build-prod
      #   env:
      #     DOCKER_BUILDKIT: 1